spring.application.name=consulting-vetoriza
spring.datasource.url=jdbc:h2:mem:vetoriza
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=consult-patient-medical
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
server.port=8081